### PR TITLE
fse20main-p3-p paper artifacts submitted for evaluation for reusable, functional, and available badges

### PR DESCRIPTION
**Pull request by rangeetpan**
fse20main-p3-p paper artifacts submitted for evaluation for reusable, functional, and available badges.

### CODE REVIEW

**Comment by letmecheckthat** [comment]
@rangeetpan Please excuse me if I am missing it, but looking at [your repository](https://github.com/rangeetpan/fse20), there are only four `.md` files and the paper. Is the source code (and results files) located elsewhere?

**Comment by rangeetpan** [comment]
@letmecheckthat, since, the source repository is very large, we have situated the repository [here](https://github.com/rangeetpan/decomposeDNNintoModules). This information has been mentioned in the Readme file and a DOI has also been created against this. Please let me know if you need any information.

**Comment by letmecheckthat** [comment]
Appreciate that, thanks. Might be worth adding to the INSTALL.md file as well, your call.

**Comment by rangeetpan** [comment]
@letmecheckthat, updated the INSTALL.md file (PR #126)

**Pull request merged**
